scan_timeout = 60
add_newline = false
command_timeout = 600

[line_break]
disabled = true

[username]
style_user = "fg:250 bold"
style_root = "red bold"
format = "[ $user]($style) "
# disabled = true
show_always = true

[directory]
truncation_symbol = " …/"
home_symbol = ""
read_only = " "
read_only_style = "#c60a93"

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[package]
format = "[$symbol$version]($style) "
symbol = "󰏓 "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold cyan"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "

[dart]
format = "[$symbol($version )]($style)"
style = "bold cyan"
symbol = " "
